local mkstr = ZO_CreateStringId
local SI = Alchemist.SI

-- output texts
mkstr(SI.NO_DISCOVERIES_AVAILABLE,          "Keine Entdeckungen m\195\182glich.")
mkstr(SI.COMBINATIONS_AVAILABLE,            "%d Kombination(en) verf\195\188gbar!")
mkstr(SI.COMBINE_THE_FOLLOWING,             "Kombiniere folgendes:")
mkstr(SI.TO_GET_THE_FOLLOWING_DISCOVERIES,  ".. um folgende Entdeckung(en) zu erzielen:")

-- reagents
mkstr(SI.BLESSED_THISTLE,   "Benediktenkraut")
mkstr(SI.BLUE_ENTOLOMA,     "Blauer Glöckling")
mkstr(SI.BUGLOSS,           "Wolfsauge")
mkstr(SI.COLUMBINE,         "Akelei")
mkstr(SI.CORN_FLOWER,       "Kornblume")
mkstr(SI.DRAGONTHORN,       "Drachendorn")
mkstr(SI.EMETIC_RUSSULA,    "Brechtäubling")
mkstr(SI.IMP_STOOL,         "Koboldschemel")
mkstr(SI.LADYS_SMOCK,       "Wiesenschaumkraut")
mkstr(SI.LUMINOUS_RUSSULA,  "Leuchttäubling")
mkstr(SI.MOUNTAIN_FLOWER,   "Bergblume")
mkstr(SI.NAMIRAS_ROT,       "Namiras Fäulnis")
mkstr(SI.NIRNROOT,          "Nirnwurz")
mkstr(SI.STINKHORN,         "Stinkmorchel")
mkstr(SI.VIOLET_COPRINUS,   "Violetter Tintling")
mkstr(SI.WATER_HYACINTH,    "Wasserhyazinthe")
mkstr(SI.WHITE_CAP,         "Weißkappe")
mkstr(SI.WORMWOOD,          "Wermut")

-- traits
mkstr(SI.DETECTION,             "Detektion")
mkstr(SI.INCREASE_ARMOR,        "Erhöht Rüstung")
mkstr(SI.INCREASE_SPELL_POWER,  "Erhöht Magiekraft")
mkstr(SI.INCREASE_SPELL_RESIST, "Erhöht Magieresistenz")
mkstr(SI.INCREASE_WEAPON_POWER, "Erhöht Waffenkraft")
mkstr(SI.INVISIBLE,             "Unsichtbarkeit")
mkstr(SI.LOWER_ARMOR,           "Verringert Rüstung")
mkstr(SI.LOWER_SPELL_CRIT,      "Verringert kritische Zaubertreffer")
mkstr(SI.LOWER_SPELL_POWER,     "Verringert Magiekraft")
mkstr(SI.LOWER_SPELL_RESIST,    "Verringert Magieresistenz")
mkstr(SI.LOWER_WEAPON_CRIT,     "Verringert kritische Waffentreffer")
mkstr(SI.LOWER_WEAPON_POWER,    "Verringert Waffenkraft")
mkstr(SI.RAVAGE_HEALTH,         "Lebensverwüstung")
mkstr(SI.RAVAGE_MAGICKA,        "Magickaverwüstung")
mkstr(SI.RAVAGE_STAMINA,        "Ausdauerverwüstung")
mkstr(SI.REDUCE_SPEED,          "Reduziert Tempo")
mkstr(SI.RESTORE_HEALTH,        "Leben wiederherstellen")
mkstr(SI.RESTORE_MAGICKA,       "Magicka wiederherstellen")
mkstr(SI.RESTORE_STAMINA,       "Ausdauer wiederherstellen")
mkstr(SI.SPEED,                 "Tempo")
mkstr(SI.SPELL_CRIT,            "Kritische Zaubertreffer")
mkstr(SI.STUN,                  "Betäubung")
mkstr(SI.UNSTOPPABLE,           "Sicherer Stand")
mkstr(SI.WEAPON_CRIT,           "Kritische Waffentreffer")
