local mkstr = ZO_CreateStringId
local SI = Alchemist.SI

-- output texts
mkstr(SI.NO_DISCOVERIES_AVAILABLE,          "No discoveries available.")
mkstr(SI.COMBINATIONS_AVAILABLE,            "%d combination(s) available!")
mkstr(SI.COMBINE_THE_FOLLOWING,             "Combine the following:")
mkstr(SI.TO_GET_THE_FOLLOWING_DISCOVERIES,  ".. to discover the following:")

-- reagents
mkstr(SI.BLESSED_THISTLE,   "Blessed Thistle")
mkstr(SI.BLUE_ENTOLOMA,     "Blue Entoloma")
mkstr(SI.BUGLOSS,           "Bugloss")
mkstr(SI.COLUMBINE,         "Columbine")
mkstr(SI.CORN_FLOWER,       "Corn Flower")
mkstr(SI.DRAGONTHORN,       "Dragonthorn")
mkstr(SI.EMETIC_RUSSULA,    "Emetic Russula")
mkstr(SI.IMP_STOOL,         "Imp Stool")
mkstr(SI.LADYS_SMOCK,       "Lady's Smock")
mkstr(SI.LUMINOUS_RUSSULA,  "Luminous Russula")
mkstr(SI.MOUNTAIN_FLOWER,   "Mountain Flower")
mkstr(SI.NAMIRAS_ROT,       "Namira's Rot")
mkstr(SI.NIRNROOT,          "Nirnroot")
mkstr(SI.STINKHORN,         "Stinkhorn")
mkstr(SI.VIOLET_COPRINUS,   "Violet Coprinus")
mkstr(SI.WATER_HYACINTH,    "Water Hyacinth")
mkstr(SI.WHITE_CAP,         "White Cap")
mkstr(SI.WORMWOOD,          "Wormwood")

-- traits
mkstr(SI.DETECTION,             "Detection")
mkstr(SI.INCREASE_ARMOR,        "Increase Armor")
mkstr(SI.INCREASE_SPELL_POWER,  "Increase Spell Power")
mkstr(SI.INCREASE_SPELL_RESIST, "Increase Spell Resist")
mkstr(SI.INCREASE_WEAPON_POWER, "Increase Weapon Power")
mkstr(SI.INVISIBLE,             "Invisible")
mkstr(SI.LOWER_ARMOR,           "Lower Armor")
mkstr(SI.LOWER_SPELL_CRIT,      "Lower Spell Crit")
mkstr(SI.LOWER_SPELL_POWER,     "Lower Spell Power")
mkstr(SI.LOWER_SPELL_RESIST,    "Lower Spell Resist")
mkstr(SI.LOWER_WEAPON_CRIT,     "Lower Weapon Crit")
mkstr(SI.LOWER_WEAPON_POWER,    "Lower Weapon Power")
mkstr(SI.RAVAGE_HEALTH,         "Ravage Health")
mkstr(SI.RAVAGE_MAGICKA,        "Ravage Magicka")
mkstr(SI.RAVAGE_STAMINA,        "Ravage Stamina")
mkstr(SI.REDUCE_SPEED,          "Reduce Speed")
mkstr(SI.RESTORE_HEALTH,        "Restore Health")
mkstr(SI.RESTORE_MAGICKA,       "Restore Magicka")
mkstr(SI.RESTORE_STAMINA,       "Restore Stamina")
mkstr(SI.SPEED,                 "Speed")
mkstr(SI.SPELL_CRIT,            "Spell Crit")
mkstr(SI.STUN,                  "Stun")
mkstr(SI.UNSTOPPABLE,           "Unstoppable")
mkstr(SI.WEAPON_CRIT,           "Weapon Crit")
