local mkstr = ZO_CreateStringId
local SI = Alchemist.SI

-- output texts
mkstr(SI.NO_DISCOVERIES_AVAILABLE,          "Aucune découverte disponible.")
mkstr(SI.COMBINATIONS_AVAILABLE,            "%d combinaisons disponibles")
mkstr(SI.COMBINE_THE_FOLLOWING,             "Combinez ceci:")
mkstr(SI.TO_GET_THE_FOLLOWING_DISCOVERIES,  ".. pour découvrir les propriétés suivantes:")

-- reagents
mkstr(SI.BLESSED_THISTLE,   "Chardon Béni")
mkstr(SI.BLUE_ENTOLOMA,     "Entoloma")
mkstr(SI.BUGLOSS,           "Noctuelle")
mkstr(SI.COLUMBINE,         "Ancolie")
mkstr(SI.CORN_FLOWER,       "Bleuet")
mkstr(SI.DRAGONTHORN,       "Épine-de-Dragon")
mkstr(SI.EMETIC_RUSSULA,    "Russule Émétique")
mkstr(SI.IMP_STOOL,         "Pied-de-Lutin")
mkstr(SI.LADYS_SMOCK,       "Cardamine des Prés")
mkstr(SI.LUMINOUS_RUSSULA,  "Russule Phosphorescente")
mkstr(SI.MOUNTAIN_FLOWER,   "Lys des Cimes")
mkstr(SI.NAMIRAS_ROT,       "Truffe de Namira")
mkstr(SI.NIRNROOT,          "Nirnrave")
mkstr(SI.STINKHORN,         "Mutinus Elegans")
mkstr(SI.VIOLET_COPRINUS,   "Coprin Violet")
mkstr(SI.WATER_HYACINTH,    "Jacinthe D'eau")
mkstr(SI.WHITE_CAP,         "Chapeau Blanc")
mkstr(SI.WORMWOOD,          "Absinthe")

-- traits
mkstr(SI.DETECTION,             "de détection^z")
mkstr(SI.INCREASE_ARMOR,        "Augmente l'armure")
mkstr(SI.INCREASE_SPELL_POWER,  "Augmente la puissance des sorts")
mkstr(SI.INCREASE_SPELL_RESIST, "Augmente la résistance aux sorts")
mkstr(SI.INCREASE_WEAPON_POWER, "Augmente la puissance de l'arme")
mkstr(SI.INVISIBLE,             "invisible^z")
mkstr(SI.LOWER_ARMOR,           "Diminue l'armure")
mkstr(SI.LOWER_SPELL_CRIT,      "Diminue le sort critique")
mkstr(SI.LOWER_SPELL_POWER,     "Diminue la puissance des sorts")
mkstr(SI.LOWER_SPELL_RESIST,    "Diminue la résistance aux sorts")
mkstr(SI.LOWER_WEAPON_CRIT,     "Diminue l'arme critique")
mkstr(SI.LOWER_WEAPON_POWER,    "Diminue la puissance de l'arme")
mkstr(SI.RAVAGE_HEALTH,         "Réduit la Santé")
mkstr(SI.RAVAGE_MAGICKA,        "Réduit la Magie")
mkstr(SI.RAVAGE_STAMINA,        "Réduit la Vigueur")
mkstr(SI.REDUCE_SPEED,          "Réduit la vitesse")
mkstr(SI.RESTORE_HEALTH,        "Rend de la Santé")
mkstr(SI.RESTORE_MAGICKA,       "Rend de la Magie")
mkstr(SI.RESTORE_STAMINA,       "Rend de la Vigueur")
mkstr(SI.SPEED,                 "Vitesse")
mkstr(SI.SPELL_CRIT,            "Sort critique")
mkstr(SI.STUN,                  "Sonne")
mkstr(SI.UNSTOPPABLE,           "Implacable")
mkstr(SI.WEAPON_CRIT,           "Arme critique")
